name: wikisentiscatter-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - ipywidgets
  - appmode
  - pip:
    - boto
    - requests
    - plotly
